### ISSUE TITLE
Change site back to 'DEFAULT' proxy

### ISSUE THREAD

**Issue by ryny24** [mubaidr/auto-proxy-extension#57]
This is by far the best proxy switching app. The only thing I don't see how to do, is how to change a site back to the 'DEFAULT' proxy.

1) I change google.com to a specific proxy.
2) I want to change it back to the 'Default setting', but Direct is the only option
3) I set a proxy for all domains, but Google stays direct. I now have to change it as well.

Thank you!

**Comment by mubaidr** [comment]
Will be available in next version. 

https://github.com/mubaidr/auto-proxy-extension/commit/7f6cf9f798dae501e489aaaba9bb5bb579669353
